name: Run Python Script Manually

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script Python à exécuter (ex: main.py ou workers/worker_2_2.py)'
        required: true
        default: 'main.py'

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
      POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
      GOOGLE_CREDENTIALS_PATH: ${{ secrets.GOOGLE_CREDENTIALS_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run chosen script
        run: |
          python ${{ github.event.inputs.script }}
